<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Khaled2Service" targetNamespace="http://ws/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ws/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
<import namespace="http://ws/" schemaLocation="khaled2_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="getResponse">
    <wsdl:part name="parameters" element="tns:getResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="get">
    <wsdl:part name="parameters" element="tns:get">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Khaled2">
    <wsdl:operation name="get">
      <wsdl:input name="get" message="tns:get">
    </wsdl:input>
      <wsdl:output name="getResponse" message="tns:getResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="Khaled2ServiceSoapBinding" type="tns:Khaled2">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="get">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="get">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Khaled2Service">
    <wsdl:port name="Khaled2Port" binding="tns:Khaled2ServiceSoapBinding">
      <soap:address location="http://localhost:8080/CDStore/services"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
